/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Banka_Otomasyon.login.musteri;
import Classes.Musteri;
import Banka_Otomasyon.Giris;
/**
 *
 * @author yakub cankurt
 */
public class Login_musteri extends javax.swing.JFrame {

    /**
     * Creates new form Login_musteri
     */
    public Login_musteri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_BORCODE = new javax.swing.JButton();
        jButton_BAKIYE = new javax.swing.JButton();
        jButton_PARAYATIR = new javax.swing.JButton();
        jButton_BORCGOR = new javax.swing.JButton();
        jButton_KARTLIMIT = new javax.swing.JButton();
        jButton_KREDI = new javax.swing.JButton();
        jTextField_PARAYATIR = new javax.swing.JTextField();
        jTextField_BORCODE = new javax.swing.JTextField();
        jButton_PARACEK = new javax.swing.JButton();
        jButton_SIFREDEGIS = new javax.swing.JButton();
        jTextField_PARACEK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_BORCODE.setText("Borç Öde");
        jButton_BORCODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BORCODEActionPerformed(evt);
            }
        });

        jButton_BAKIYE.setText("Bakiye Öğren");
        jButton_BAKIYE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BAKIYEActionPerformed(evt);
            }
        });

        jButton_PARAYATIR.setText("Para Yatır");
        jButton_PARAYATIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PARAYATIRActionPerformed(evt);
            }
        });

        jButton_BORCGOR.setText("Borç Göster");
        jButton_BORCGOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BORCGORActionPerformed(evt);
            }
        });

        jButton_KARTLIMIT.setText("Kart Limit İşlemleri");
        jButton_KARTLIMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KARTLIMITActionPerformed(evt);
            }
        });

        jButton_KREDI.setText("Kredi Talep");
        jButton_KREDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KREDIActionPerformed(evt);
            }
        });

        jTextField_PARAYATIR.setText(" ");
        jTextField_PARAYATIR.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_PARAYATIRİnputMethodTextChanged(evt);
            }
        });
        jTextField_PARAYATIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PARAYATIRActionPerformed(evt);
            }
        });
        jTextField_PARAYATIR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PARAYATIRKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PARAYATIRKeyTyped(evt);
            }
        });

        jTextField_BORCODE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BORCODEKeyReleased(evt);
            }
        });

        jButton_PARACEK.setText("Para Çek");
        jButton_PARACEK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PARACEKActionPerformed(evt);
            }
        });

        jButton_SIFREDEGIS.setText("Şifre Değiştir");

        jTextField_PARACEK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_PARACEKKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_PARAYATIR, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_PARAYATIR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton_KARTLIMIT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_BAKIYE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_PARACEK, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_PARACEK))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_BORCODE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_BORCODE)))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_BORCGOR, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jButton_KREDI, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jButton_SIFREDEGIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_BORCGOR)
                    .addComponent(jButton_BAKIYE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_PARAYATIR)
                    .addComponent(jButton_KARTLIMIT)
                    .addComponent(jTextField_PARAYATIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_KREDI)
                    .addComponent(jButton_BORCODE)
                    .addComponent(jTextField_BORCODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_PARACEK)
                    .addComponent(jButton_SIFREDEGIS)
                    .addComponent(jTextField_PARACEK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PARAYATIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PARAYATIRActionPerformed
        Musteri x = new Musteri();
        x.paraYatir(Giris.idMusteri,Double.parseDouble(jTextField_PARAYATIR.getText()));
        jTextField_PARAYATIR.setText("");
    }//GEN-LAST:event_jButton_PARAYATIRActionPerformed

    private void jButton_BAKIYEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BAKIYEActionPerformed
        Musteri x = new Musteri();
       x.displayBakiye(Giris.idMusteri);
    }//GEN-LAST:event_jButton_BAKIYEActionPerformed

    private void jButton_KREDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KREDIActionPerformed
        Kredi_Talep x = new Kredi_Talep();
                    setVisible(false);
                    x.setVisible(true);
    }//GEN-LAST:event_jButton_KREDIActionPerformed

    private void jButton_KARTLIMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KARTLIMITActionPerformed
        Kart_Limit_Secenek x = new Kart_Limit_Secenek();
        setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_jButton_KARTLIMITActionPerformed

    private void jButton_BORCGORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BORCGORActionPerformed
       Musteri x = new Musteri();
       x.displayBorc(Giris.idMusteri);
       
    }//GEN-LAST:event_jButton_BORCGORActionPerformed

    private void jTextField_PARAYATIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PARAYATIRActionPerformed
        
    }//GEN-LAST:event_jTextField_PARAYATIRActionPerformed

    private void jTextField_PARAYATIRİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_PARAYATIRİnputMethodTextChanged
        
    }//GEN-LAST:event_jTextField_PARAYATIRİnputMethodTextChanged

    private void jTextField_PARAYATIRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PARAYATIRKeyTyped

    }//GEN-LAST:event_jTextField_PARAYATIRKeyTyped

    private void jTextField_PARAYATIRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PARAYATIRKeyReleased
        try {
            double x = Double.parseDouble(jTextField_PARAYATIR.getText());
        } catch (NumberFormatException nfe) {
            jTextField_PARAYATIR.setText("");
        }
    }//GEN-LAST:event_jTextField_PARAYATIRKeyReleased

    private void jTextField_BORCODEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BORCODEKeyReleased
        try {
            double x = Double.parseDouble(jTextField_PARAYATIR.getText());
        } catch (NumberFormatException nfe) {
            jTextField_PARAYATIR.setText("");
        }
    }//GEN-LAST:event_jTextField_BORCODEKeyReleased

    private void jButton_BORCODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BORCODEActionPerformed
        Musteri x = new Musteri();
        x.borcOde(Giris.idMusteri,Double.parseDouble(jTextField_BORCODE.getText()));
        jTextField_BORCODE.setText("");
    }//GEN-LAST:event_jButton_BORCODEActionPerformed

    private void jTextField_PARACEKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PARACEKKeyReleased
        try {
            double x = Double.parseDouble(jTextField_PARAYATIR.getText());
        } catch (NumberFormatException nfe) {
            jTextField_PARAYATIR.setText("");
        }
    }//GEN-LAST:event_jTextField_PARACEKKeyReleased

    private void jButton_PARACEKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PARACEKActionPerformed
        Musteri x = new Musteri();
        x.paraCek(Giris.idMusteri,Double.parseDouble(jTextField_PARACEK.getText()));
        jTextField_PARACEK.setText("");
    }//GEN-LAST:event_jButton_PARACEKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_musteri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_musteri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BAKIYE;
    private javax.swing.JButton jButton_BORCGOR;
    private javax.swing.JButton jButton_BORCODE;
    private javax.swing.JButton jButton_KARTLIMIT;
    private javax.swing.JButton jButton_KREDI;
    private javax.swing.JButton jButton_PARACEK;
    private javax.swing.JButton jButton_PARAYATIR;
    private javax.swing.JButton jButton_SIFREDEGIS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_BORCODE;
    private javax.swing.JTextField jTextField_PARACEK;
    private javax.swing.JTextField jTextField_PARAYATIR;
    // End of variables declaration//GEN-END:variables
}
